#define TYPE_FIXNUM 1
#define TYPE_SYMBOL 2
#define TYPE_FUNCTION 3
#define TYPE_CONS 4
#define TYPE_UNKNOWN 999

#define TYPE_MASK 0x7
#define TYPE_TAG_FIXNUM 0x1L
#define TYPE_TAG_FUNCTION 0x2L
#define TYPE_TAG_CLOSURE 0x3L
#define TYPE_TAG_SYMBOL 0x4L
#define TYPE_TAG_CONS 0x5L

#define NAMESPACE_VARIABLE 0
#define NAMESPACE_FUNCTION 1

typedef int RUNTIME_TYPE;
typedef int NAMESPACE_TYPE;
